export const challenges = [
  { id: "ringTryOn", emoji: "💍", label: "Get customer to try on jewelry", delta: 1 },
  { id: "sellAccessory", emoji: "👜", label: "Sell a purse/accessory", delta: 1 },
  { id: "upsellWarranty", emoji: "🛡️", label: "Sell protection/warranty", delta: 1 },
  { id: "bundleSale", emoji: "🎁", label: "Create a bundle sale", delta: 1 },
  { id: "giftWrap", emoji: "🎀", label: "Offer gift wrapping", delta: 1 },
  { id: "newsletter", emoji: "📧", label: "Sign customer up for newsletter", delta: 1 },
  { id: "referral", emoji: "🤝", label: "Get a customer referral", delta: 1 },
  { id: "onlineOrder", emoji: "💻", label: "Place an online order", delta: 1 },
  { id: "socialShare", emoji: "📱", label: "Get a social media share", delta: 1 },
  { id: "accessoryAddOn", emoji: "🔗", label: "Add accessory add-on", delta: 1 },
  { id: "returnToPurchase", emoji: "🔁", label: "Convert a return into purchase", delta: 1 },
  { id: "giftCardSale", emoji: "💳", label: "Sell a gift card", delta: 1 },
  { id: "membership", emoji: "🏷️", label: "Sell a store membership/club", delta: 1 },
  { id: "demoShown", emoji: "🎬", label: "Show product demo", delta: 1 },
  { id: "crossSell", emoji: "➕", label: "Cross-sell another category", delta: 1 },
  { id: "firstTimeBuyer", emoji: "🌟", label: "First-time buyer conversion", delta: 1 },
  { id: "paymentPlan", emoji: "🧾", label: "Sell a payment plan", delta: 1 },
  { id: "fastCheckout", emoji: "⚡", label: "Fast/priority checkout", delta: 1 },
  { id: "feedback", emoji: "✍️", label: "Collect customer feedback", delta: 1 },
  { id: "survey", emoji: "📋", label: "Get customer survey completion", delta: 1 },
  { id: "upsellPremium", emoji: "💎", label: "Upgrade to premium product", delta: 1 },
  { id: "addOnService", emoji: "🔧", label: "Sell service add-on", delta: 1 },
  { id: "inStorePickup", emoji: "🏬", label: "Convert to in-store pickup", delta: 1 },
  { id: "promoApplied", emoji: "🏷️", label: "Apply a promotion/sale", delta: 1 },
  { id: "thankYouNote", emoji: "💌", label: "Add a personalized thank-you", delta: 1 }
];